[package]
name = "IPcow"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
ipnetwork = "*"
itertools = "*"
futures = "*"


[lib]
name = "sockparse"
path = "src/sockparse.rs"
